name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "4.3" }
          - { os: macos-latest, r: "4.3" }
          - { os: windows-latest, r: "4.3" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)

      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual --as-cran

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: R-CMD-check-results
          path: "*.Rcheck/"
